### ISSUE TITLE
Add option to enable https

### ISSUE THREAD

**Issue by Its-Alex** [harobed/ansible-role-sentry#4]
Maybe add a variable that can be set to enable https on sentry ?

**Comment by harobed** [comment]
>  to enable https on sentry ?

How do you want to enable https on Sentry?

If you use [nginx-proxy](https://github.com/jwilder/nginx-proxy) (you can also [ansible-role-nginx-proxy](https://github.com/harobed/ansible-role-nginx-proxy)) you can set `sentry_letsencrypt_host` and `sentry_letsencrypt_email` to enable let's encrypt to add https support.

Otherwise you can configure Nginx, Apache or Caddy and connect it to port `9000`.

@Its-Alex Does that answer your question?

**Comment by Its-Alex** [comment]
I speak about [here](https://github.com/harobed/ansible-role-sentry/blob/master/templates/sentry-config.yml.j2#L1) maybe you can replace by

```
{% if sentry_letsencrypt_host %}
system.url-prefix: https://{{ sentry_url_domain }}
{% else %}
system.url-prefix: http://{{ sentry_url_domain }}
{% endif %}
```

**Comment by harobed** [comment]
You can set `sentry_url_prefix` manually, like that:

```
sentry_url_prefix: "https://{{ sentry_virtual_host }}"
sentry_letsencrypt_host: sentry.example.com
sentry_letsencrypt_email: contact@example.com
```

I prefer to be [KISS](https://en.wikipedia.org/wiki/KISS_principle), then configure `sentry_url_prefix` manually.

@Its-Alex How do you react to that?
